language: python
install:
  - pip install requests
  - pip install beautifulsoup4
  - pip install pandas
  - pip install matplotlib
  - pip install xlwt
  - pip install -e . --progress-bar off
script: python -c "import kcrawler"
